ROVPROJECTREPORT/Models/ErrorViewModel.cs
using System;

namespace ROVPROJECTREPORT.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ROVPROJECTREPORT/Models/NewROVContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ROVPROJECTREPORT.Models
{
    public partial class NewROVContext : DbContext
    {
        public NewROVContext()
        {
        }

        public NewROVContext(DbContextOptions<NewROVContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Reports> Reports { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Reports>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Details)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Recreate)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Type)
                    .HasMaxLength(20)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

ROVPROJECTREPORT/Models/Reports.cs
using System;
using System.Collections.Generic;

namespace ROVPROJECTREPORT.Models
{
    public partial class Reports
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Recreate { get; set; }
        public string Type { get; set; }
    }
}

ROVPROJECTREPORT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ROVPROJECTREPORT.Models;

namespace ROVPROJECTREPORT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ROVPROJECTREPORT/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ROVPROJECTREPORT.Data;
using ROVPROJECTREPORT.Models;

namespace ROVPROJECTREPORT.Controllers
{
    public class ReportsController : Controller
    {
        private readonly ROVPROJECTREPORTContext _context;

        public ReportsController(ROVPROJECTREPORTContext context)
        {
            _context = context;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reports.ToListAsync());
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reports = await _context.Reports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reports == null)
            {
                return NotFound();
            }

            return View(reports);
        }

        // GET: Reports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Details,Recreate,Type")] Reports reports)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reports);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reports);
        }

        // GET: Reports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reports = await _context.Reports.FindAsync(id);
            if (reports == null)
            {
                return NotFound();
            }
            return View(reports);
        }

        // POST: Reports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Details,Recreate,Type")] Reports reports)
        {
            if (id != reports.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reports);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportsExists(reports.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reports);
        }

        // GET: Reports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reports = await _context.Reports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reports == null)
            {
                return NotFound();
            }

            return View(reports);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reports = await _context.Reports.FindAsync(id);
            _context.Reports.Remove(reports);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportsExists(int id)
        {
            return _context.Reports.Any(e => e.Id == id);
        }
    }
}

ROVPROJECTREPORT/Views/Home/Index.cshtml
@model IEnumerable<ROVPROJECTREPORT.Models.Reports>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">
    <div>
        <img src="~/img/19199050.jpg" style="width: 400px; display: block; margin-left: auto; margin-right: auto;">
    </div>
    <div>
        <div class="alert alert-danger" role="alert">
            When reporting success! You will receive a response no more than 24 hours
        </div>
    </div>
    <h1 class="text-center">Account ROV</h1>
    <div class="text-center">
        <button type="button" class="btn btn-primary btn-lg active">Report bugs</button>
        <button type="button" class="btn btn-danger btn-lg">Reset password</button>
    </div><br />

    <div class="card-group">
        <div class="card">
            <div class="card-body">
                <h5>REPORT BUGS</h5>

                <div class="form-group">
                    <label for="inputAddress">Enter the main body of your report here:</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>

                <form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="Index">
                    <div class="form-group">
                        <label for="inputProblem">Select a category</label>
                        <select id="inputProblem" class="form-control">
                            <option selected>Choose...</option>
                            <option>Billing Issue</option>
                            <option>Text & Audio</option>
                            <option>Technical</option>
                            <option>Lost Items</option>
                            <option>Graphical</option>
                            <option>Gameplay</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="inputAddress">Enter the main body of your report here:</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="inputAddress2">Please provide steps to recreate the bug:</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <hr />
                    @ViewBag.Name
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5>RESET PASSWORD</h5>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputPassword">Old Password</label>
                        <input type="password" class="form-control" id="inputEmail4">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputPassword">New Password</label>
                        <input type="password" class="form-control" id="inputPassword4">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Reset</button>
            </div>
        </div>
    </div><br />

    <h3>Report Status</h3><br />
    <table class="table">
        <thead>
            <tr>
                <th scope="col" style="width: 10%">ID</th>
                <th scope="col" style="width: 50%">Title</th>
                <th scope="col" style="width: 20%">Date</th>
                <th scope="col" style="width: 20%">Status</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>A</td>
            </tr>
        </tbody>
    </table>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ROVPROJECTREPORT/Views/Reports/Create.cshtml
@model ROVPROJECTREPORT.Models.Reports

@{
    ViewData["Title"] = "Create";
}


<h2>Reports</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" for="inputAddress">ID</label>
                <input asp-for="Id" type="number" class="form-control" id="inputAddress">
            </div>
            <div class="form-group">
                <label asp-for="Title" for="inputAddress">Title</label>
                <input asp-for="Title" type="text" class="form-control" id="inputAddress">
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label">Select a category</label>
                <select id="inputProblem" asp-for="Type" class="form-control">
                    <option selected>Choose...</option>
                    <option>Billing Issue</option>
                    <option>Text & Audio</option>
                    <option>Technical</option>
                    <option>Lost Items</option>
                    <option>Graphical</option>
                    <option>Gameplay</option>
                </select>
            </div>


            <div class="form-group">
                <label asp-for="Details">Enter the main body of your report here:</label>
                <textarea class="form-control" asp-for="Details" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Recreate" for="inputAddress2">Please provide steps to recreate the bug:</label>
                <textarea asp-for="Recreate" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
            <hr />
            @ViewBag.Name
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to main page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ROVPROJECTREPORT/Views/Reports/Delete.cshtml
@model ROVPROJECTREPORT.Models.Reports

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reports</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recreate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recreate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ROVPROJECTREPORT/Views/Reports/Details.cshtml
@model ROVPROJECTREPORT.Models.Reports

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reports</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recreate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recreate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ROVPROJECTREPORT/Views/Reports/Edit.cshtml
@model ROVPROJECTREPORT.Models.Reports

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reports</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Recreate" class="control-label"></label>
                <input asp-for="Recreate" class="form-control" />
                <span asp-validation-for="Recreate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ROVPROJECTREPORT/Views/Reports/Index.cshtml
@model IEnumerable<ROVPROJECTREPORT.Models.Reports>
@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">
    <div>
        <img src="~/img/19199050.jpg" style="width: 400px; display: block; margin-left: auto; margin-right: auto;">
    </div>
    <div>
        <div class="alert alert-danger" role="alert">
            When reporting success! You will receive a response no more than 24 hours
        </div>
    </div>
    <h1 class="text-center">Account ROV</h1>
    <div class="text-center">
        <a href="/reports/create"><button type="button" class="btn btn-primary btn-lg active">Report bugs</button></a>
    </div><br />

    

    <h3>Report Status</h3><br />
    <table class="table">
        <thead>
            <tr>
                <th scope="col" style="width: 10%">ID</th>
                <th scope="col" style="width: 50%">Title</th>
                <th scope="col" style="width: 20%">Type</th>
                <th scope="col" style="width: 20%">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td class="text-warning">
                        In process
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ROVPROJECTREPORT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ROVPROJECTREPORT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Reports" asp-action="Index">ROVPROJECTREPORT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2563 - ROVPROJECTREPORT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Theme</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>